export default {
  pageHeader: 'div.c8y-ui-title>h1',
  progressBar: 'c8y-progress-bar',
  alertOutlet: 'c8y-alert-outlet div strong',

  // #######[Links]###############
  propertyLibraryLink: "button[title='Asset properties']",
  localizationLink: "button[title='Localization']",
  assetsLink: '#navigator_node_assets',
  configurationLink: '#navigator_node_configuration',
  digitalTwinLibraryLink: "button[title='Digital twin library']",
  assetTypesLink: "button[title='Asset models']",
  helpIcon: "button[data-cy='data-grid--help-filters']",
  homePageLink: "button[title='Home']",
  subassetsPageLink: "a[title='Subassets']",
  assetTreePageLink: "a[title='Asset tree']",
  helpIconAssetModelKey: "button[data-cy='help-asset-model-key']",
  helpIconAddChildAssetModel: "button[data-cy='help-add-child-asset-model']",
  helpIconAddAssetProperty: "button[data-cy='help-add-asset-property']",
  helpIconComplexProperty: "button[data-cy='help-complex-property']",
  alertPopupConfirmButton: ".alert-footer> button[title='Confirm']",
  chooseOnMapButton: "button[data-cy='location-type-choose-on-map']",
  mapLink: "div[data-cy='location-type-map']",

  // ########[Buttons]#############
  configureCloumnsButton: "button[title='Configure columns']",
  reloadButton: "button[title='Reload']",
  cancelEditPopupButton: "button[title='Cancel']",
  confirmEditPopupButton: "button[title='Confirm']",
  closeAlert: ".close > [aria-hidden='true']",
  closeAlert_showDetails: "[title='Show details']",
  backButton: 'button[data-cy="back"]',
  importButton: 'button[data-cy="next"][title="Import"]',
  nextButton: 'button[data-cy="next"]',
  editGridButton: "button i[c8yicon='pencil']",
  deleteGridButton: "button i[c8yicon='delete']",
  cancelDeletePopupButton: "c8y-confirm-modal button[title='Cancel']",
  confirmDeletePopupButton: "c8y-confirm-modal button[title='Confirm']",
  activeFiltersButton: "button[title='Active filters']",
  clearFilterButton: "button[title='Clear all filters']"
};
