name: Widget build

on:
  workflow_call:
    inputs:
      build_command:
        description: "Command to build the application. E.g: yarn build:dtm"
        required: true
        type: string
      app_file_name_prefix:
        description: "Desired name prefix for the output build package. E.g: for prefix dtm-ui, ouput will be dtm-ui-1017.0.1"
        required: true
        type: string
      app_context_path:
        description: "Context path of the application. E.g: digital-twin-manager"
        required: false
        type: string
      upload_artifact:
        description: "flag indicating to upload the built artifact or not"
        type: boolean
      build_number:
        description: "Use the provided build number in the version"
        type: string
      skip_run:
        description: "use to skip the workflow run"
        type: boolean
        default: false
    outputs:
      file_name:
        description: "name of the uploaded artifact"
        value: ${{ jobs.build-widget.outputs.file_name}}

jobs:
  build-widget:
    if: ${{inputs.skip_run != true }}
    runs-on: [ubuntu-latest]
    outputs:
      file_name: ${{ steps.compose-file-name.outputs.app_file_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Compose file name
        id: compose-file-name
        run: |
          version=`jq -r '.version' package.json`
          echo "app_file_name=${{ inputs.app_file_name_prefix }}-$version" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          yarn clean:dist
          ${{ inputs.build_command }}

      - name: Upload artifact
        if: ${{ inputs.upload_artifact == true }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.compose-file-name.outputs.app_file_name }}
          path: dist/${{ steps.compose-file-name.outputs.app_file_name }}.zip
          retention-days: 7

  status-check:
    needs: [build-widget]
    if: always()
    runs-on: [ubuntu-latest]
    steps:
      - name: Verify step status
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
