name: Widget unit test skip

on:
  pull_request:
    paths-ignore:
      - asset-properties-widget/**
    branches:
      - develop

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-test-widget.yml
    with:
      skip_run: true
      test_command: ""
